version: '3.9'

services:

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d

  build: &build
    build:
      context: .
      args:
        NODE_IMAGE: "node:${NODE_VERSION:-18}-alpine"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: password
      CI: $CI
    volumes:
      - ../../:/app
    working_dir: /app/packages/example
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - db
    command: sh -c "node /app/packages/cli/lib/index.js --config config.json && ./check-git-diff.sh"

  watch:
    <<: *build
    command: npx pgtyped --watch --config config.json

  test:
    <<: *build
    depends_on:
      - build
    command: npx jest index.test.ts

  test-cjs:
    <<: *build
    depends_on:
      - build
    command: npx jest -c jest-cjs.config.ts index.test.ts

